name: NodeJS

on:
  push:
    branches: [ "main" ]
    paths: ["app/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["app/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm i
        cd frontend
        npm i 
        npm run build
        
