name: NodeJS

on:
  push:
    branches: [ "main" ]
    paths: ["app/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["app/**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Build
      run: |
        cd app
        ls -l content
        npm i 
        npm i front-matter marked@latest highlight.js@latest
        npm run build
        ls -l public/

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to S3
      run: |
        aws s3 sync .app/public s3://nodejs-static-website-bucket-01 --delete

